namespace MarioLucci.Ituran.Api.Models.Entities
{
    public class Quotes
    {
        public string USDAED { get; set; }
        public string USDAFN { get; set; }
        public string USDALL { get; set; }
        public string USDAMD { get; set; }
        public string USDANG { get; set; }
        public string USDAOA { get; set; }
        public string USDARS { get; set; }
        public string USDAUD { get; set; }
        public string USDAWG { get; set; }
        public string USDAZN { get; set; }
        public string USDBAM { get; set; }
        public string USDBBD { get; set; }
        public string USDBDT { get; set; }
        public string USDBGN { get; set; }
        public string USDBHD { get; set; }
        public string USDBIF { get; set; }
        public string USDBMD { get; set; }
        public string USDBND { get; set; }
        public string USDBOB { get; set; }
        public string USDBRL { get; set; }
        public string USDBSD { get; set; }
        public string USDBTC { get; set; }
        public string USDBTN { get; set; }
        public string USDBWP { get; set; }
        public string USDBYN { get; set; }
        public string USDBYR { get; set; }
        public string USDBZD { get; set; }
        public string USDCAD { get; set; }
        public string USDCDF { get; set; }
        public string USDCHF { get; set; }
        public string USDCLF { get; set; }
        public string USDCLP { get; set; }
        public string USDCNY { get; set; }
        public string USDCOP { get; set; }
        public string USDCRC { get; set; }
        public string USDCUC { get; set; }
        public string USDCUP { get; set; }
        public string USDCVE { get; set; }
        public string USDCZK { get; set; }
        public string USDDJF { get; set; }
        public string USDDKK { get; set; }
        public string USDDOP { get; set; }
        public string USDDZD { get; set; }
        public string USDEGP { get; set; }
        public string USDERN { get; set; }
        public string USDETB { get; set; }
        public string USDEUR { get; set; }
        public string USDFJD { get; set; }
        public string USDFKP { get; set; }
        public string USDGBP { get; set; }
        public string USDGEL { get; set; }
        public string USDGGP { get; set; }
        public string USDGHS { get; set; }
        public string USDGIP { get; set; }
        public string USDGMD { get; set; }
        public string USDGNF { get; set; }
        public string USDGTQ { get; set; }
        public string USDGYD { get; set; }
        public string USDHKD { get; set; }
        public string USDHNL { get; set; }
        public string USDHRK { get; set; }
        public string USDHTG { get; set; }
        public string USDHUF { get; set; }
        public string USDIDR { get; set; }
        public string USDILS { get; set; }
        public string USDIMP { get; set; }
        public string USDINR { get; set; }
        public string USDIQD { get; set; }
        public string USDIRR { get; set; }
        public string USDISK { get; set; }
        public string USDJEP { get; set; }
        public string USDJMD { get; set; }
        public string USDJOD { get; set; }
        public string USDJPY { get; set; }
        public string USDKES { get; set; }
        public string USDKGS { get; set; }
        public string USDKHR { get; set; }
        public string USDKMF { get; set; }
        public string USDKPW { get; set; }
        public string USDKRW { get; set; }
        public string USDKWD { get; set; }
        public string USDKYD { get; set; }
        public string USDKZT { get; set; }
        public string USDLAK { get; set; }
        public string USDLBP { get; set; }
        public string USDLKR { get; set; }
        public string USDLRD { get; set; }
        public string USDLSL { get; set; }
        public string USDLTL { get; set; }
        public string USDLVL { get; set; }
        public string USDLYD { get; set; }
        public string USDMAD { get; set; }
        public string USDMDL { get; set; }
        public string USDMGA { get; set; }
        public string USDMKD { get; set; }
        public string USDMMK { get; set; }
        public string USDMNT { get; set; }
        public string USDMOP { get; set; }
        public string USDMRO { get; set; }
        public string USDMUR { get; set; }
        public string USDMVR { get; set; }
        public string USDMWK { get; set; }
        public string USDMXN { get; set; }
        public string USDMYR { get; set; }
        public string USDMZN { get; set; }
        public string USDNAD { get; set; }
        public string USDNGN { get; set; }
        public string USDNIO { get; set; }
        public string USDNOK { get; set; }
        public string USDNPR { get; set; }
        public string USDNZD { get; set; }
        public string USDOMR { get; set; }
        public string USDPAB { get; set; }
        public string USDPEN { get; set; }
        public string USDPGK { get; set; }
        public string USDPHP { get; set; }
        public string USDPKR { get; set; }
        public string USDPLN { get; set; }
        public string USDPYG { get; set; }
        public string USDQAR { get; set; }
        public string USDRON { get; set; }
        public string USDRSD { get; set; }
        public string USDRUB { get; set; }
        public string USDRWF { get; set; }
        public string USDSAR { get; set; }
        public string USDSBD { get; set; }
        public string USDSCR { get; set; }
        public string USDSDG { get; set; }
        public string USDSEK { get; set; }
        public string USDSGD { get; set; }
        public string USDSHP { get; set; }
        public string USDSLL { get; set; }
        public string USDSOS { get; set; }
        public string USDSRD { get; set; }
        public string USDSTD { get; set; }
        public string USDSVC { get; set; }
        public string USDSYP { get; set; }
        public string USDSZL { get; set; }
        public string USDTHB { get; set; }
        public string USDTJS { get; set; }
        public string USDTMT { get; set; }
        public string USDTND { get; set; }
        public string USDTOP { get; set; }
        public string USDTRY { get; set; }
        public string USDTTD { get; set; }
        public string USDTWD { get; set; }
        public string USDTZS { get; set; }
        public string USDUAH { get; set; }
        public string USDUGX { get; set; }
        public string USDUSD { get; set; }
        public string USDUYU { get; set; }
        public string USDUZS { get; set; }
        public string USDVEF { get; set; }
        public string USDVND { get; set; }
        public string USDVUV { get; set; }
        public string USDWST { get; set; }
        public string USDXAF { get; set; }
        public string USDXAG { get; set; }
        public string USDXAU { get; set; }
        public string USDXCD { get; set; }
        public string USDXDR { get; set; }
        public string USDXOF { get; set; }
        public string USDXPF { get; set; }
        public string USDYER { get; set; }
        public string USDZAR { get; set; }
        public string USDZMK { get; set; }
        public string USDZMW { get; set; }
        public string USDZWL { get; set; }
    }
}